version: "1.0"

services:
    php-apache-5:
        container_name: php-apache-5
        build:
            context: ./php5
        image: php5-apache
        ports:
            - "85:80"
        volumes:
            - /var/www/php5:/var/www/html
        networks:
            - ubuntu-network
        restart: unless-stopped
    php-apache-72:
        container_name: php-apache-72
        build:
            context: ./php72
        image: php72-apache
        ports:
            - "8585:80"
            - "80:80"
        volumes:
            - /var/www/php7:/var/www/html
        networks:
            - ubuntu-network
        restart: unless-stopped
    mysql-5-database:
        image: mysql:5.7-debian
        platform: "linux/amd64"
        container_name: mysql-5-database
        restart: always
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: upilproject
            MYSQL_PASSWORD: unitproject
            MYSQL_USER: upilproject
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - '3305:3306' 
        volumes:
            - './mysql5/db/data:/var/lib/mysql'
            - './mysql5/db/my.cnf:/etc/mysql/conf.d/my.cnf'
            - './mysql5/db/sql:/docker-entrypoint-initdb.d'
        networks:
            - ubuntu-network
networks:
    ubuntu-network:
        driver: bridge